# Utiliser un moteur d'exécution officiel de Python comme image mère

FROM continuumio/anaconda3:latest

#Commande

RUN pip install pygeocoder \
	&& mkdir /app /logs


# Définir le répertoire de travail sur /app
          
WORKDIR /app

